### ISSUE TITLE
Make pod spec of runner configurable

### ISSUE THREAD

**Issue by rafalgalaw** [mercedes-benz/garm-provider-k8s#2]
### What steps did you take and what happened?

Right now the pod is generated within the go code. This is fine for now, however one can not customize the pod with additional env, init or sidecar containers.

### What did you expect to happen?

I want to be able to configure a PodTemplate in the providers config, which gets merged/overwrites the default pod generated in the go code.
Things to consider:
- not all envs should be overwriteable by custom PodTemplate
- Some PodTemplate fields need to be set by the provider and can not be overwritten.

**Comment by bavarianbidi** [comment]
with `v0.1.0` it's possible to define a pod template spec
